/*
 * Bazinga, a custom Discord desktop client
 * Copyright (c) 2026 bliper2 and Bazinga contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// Writes docs/PLUGINS.md and the website docs/index.html from the plugin and theme sources, so they never drift from
// the code. Run `bun run docs`. `bun run docs:check` fails when a file is out of date (used in CI).

import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dirname, "../..");
const PLUGINS_DIR = join(ROOT, "plugins");
const OUTPUT = join(ROOT, "docs/PLUGINS.md");
const SITE_OUTPUT = join(ROOT, "docs/index.html");

export interface PluginInfo {
    name: string;
    description: string;
    tags: string[];
    enabledByDefault: boolean;
}

const unescape = (text: string) => text.replace(/\\(["\\])/g, "$1");

/** Reads the name, description, tags and default state from a plugin's index file. */
export function parsePlugin(source: string): PluginInfo | null {
    const head = /definePlugin\(\{\s*name:\s*"((?:[^"\\]|\\.)*)",\s*description:\s*"((?:[^"\\]|\\.)*)"/.exec(source);
    if (!head) return null;

    const tags = /tags:\s*\[([^\]]*)\]/.exec(source)?.[1].match(/"([^"]+)"/g)?.map(t => t.slice(1, -1)) ?? [];
    return {
        name: unescape(head[1]),
        description: unescape(head[2]),
        tags,
        enabledByDefault: /enabledByDefault:\s*true/.test(source)
    };
}

export function readPlugins(): PluginInfo[] {
    const plugins: PluginInfo[] = [];
    for (const entry of readdirSync(PLUGINS_DIR, { withFileTypes: true })) {
        if (!entry.isDirectory() || entry.name.startsWith("_")) continue;

        const file = ["index.tsx", "index.ts"].map(f => join(PLUGINS_DIR, entry.name, f)).find(existsSync);
        const info = file && parsePlugin(readFileSync(file, "utf-8"));
        if (!info) throw new Error(`Could not read the plugin in plugins/${entry.name}`);
        plugins.push(info);
    }
    return plugins.sort((a, b) => a.name.localeCompare(b.name));
}

export function readThemes() {
    const source = readFileSync(join(ROOT, "src/main/bundledThemes.ts"), "utf-8");
    return [...source.matchAll(/name:\s*"([^"]+)",\s*description:\s*"([^"]+)"/g)].map(m => ({ name: m[1], description: m[2] }));
}

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

export function buildDocument(plugins: PluginInfo[], themes: { name: string; description: string; }[]) {
    const rows = plugins.map(p => `| **${p.name}** | ${cell(p.description)} | ${p.enabledByDefault ? "Yes" : "No"} |`);
    const themeRows = themes.map(t => `| **${t.name}** | ${cell(t.description)} |`);

    return `# Bazinga plugins and themes

<!-- This file is generated by \`bun run docs\`. Do not edit it by hand. -->

Search the Plugins page for "bazinga" to list these in the app.

## Plugins (${plugins.length})

| Plugin | What it does | On by default |
| ------ | ------------ | ------------- |
${rows.join("\n")}

## Themes by orgeco (${themes.length})

Turn them on under Settings, Themes.

| Theme | Look |
| ----- | ---- |
${themeRows.join("\n")}
`;
}

const escapeHtml = (text: string) =>
    text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** The project website: one self-contained page with no scripts from other sites. */
export function buildSite(plugins: PluginInfo[], themes: { name: string; description: string; }[]) {
    const pluginItems = plugins
        .map(
            p =>
                `<li data-text="${escapeHtml(`${p.name} ${p.description} ${p.tags.join(" ")}`.toLowerCase())}"><strong>${escapeHtml(p.name)}</strong>${
                    p.enabledByDefault ? ' <span class="badge">on by default</span>' : ""
                }<span>${escapeHtml(p.description)}</span></li>`
        )
        .join("\n");
    const themeItems = themes.map(t => `<li><strong>${escapeHtml(t.name)}</strong><span>${escapeHtml(t.description)}</span></li>`).join("\n");

    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bazinga</title>
<meta name="description" content="A Discord desktop client with Equicord built in, ${plugins.length} extra plugins and themes by orgeco.">
<!-- This file is generated by \`bun run docs\`. Do not edit it by hand. -->
<style>
:root { color-scheme: light dark; --bg: #fafafa; --fg: #1d1d21; --muted: #666a73; --card: #fff; --line: #e1e3e8; --accent: #e08a00; }
@media (prefers-color-scheme: dark) { :root { --bg: #0f1117; --fg: #e8e9ee; --muted: #9aa0ad; --card: #171a22; --line: #272b36; --accent: #f5a524; } }
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--fg); font: 16px/1.55 system-ui, sans-serif; }
main { max-width: 960px; margin: 0 auto; padding: 32px 16px 64px; }
header { display: flex; align-items: center; gap: 20px; flex-wrap: wrap; }
header img { width: 96px; height: 96px; border-radius: 20px; }
h1 { margin: 0; font-size: 2.4rem; }
h2 { margin-top: 48px; }
p.lead { margin: 4px 0 0; color: var(--muted); font-size: 1.1rem; }
.buttons { display: flex; gap: 12px; flex-wrap: wrap; margin: 20px 0; }
a.button { padding: 10px 18px; border-radius: 8px; background: var(--accent); color: #1a1300; font-weight: 600; text-decoration: none; }
a.button.secondary { background: none; border: 1px solid var(--line); color: var(--fg); }
.shots { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 12px; margin-top: 24px; }
.shots img { width: 100%; border-radius: 10px; border: 1px solid var(--line); }
input[type=search] { width: 100%; padding: 10px 12px; border: 1px solid var(--line); border-radius: 8px; background: var(--card); color: var(--fg); font: inherit; }
ul.list { list-style: none; margin: 12px 0 0; padding: 0; display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 10px; }
ul.list li { display: flex; flex-direction: column; gap: 2px; padding: 12px 14px; border: 1px solid var(--line); border-radius: 10px; background: var(--card); }
ul.list li span { color: var(--muted); font-size: 0.9rem; }
.badge { align-self: flex-start; padding: 1px 6px; border-radius: 4px; background: var(--accent); color: #1a1300 !important; font-size: 0.7rem !important; font-weight: 700; }
footer { margin-top: 56px; color: var(--muted); font-size: 0.9rem; }
a { color: var(--accent); }
</style>
</head>
<body>
<main>
<header>
<img src="logo.png" alt="Bazinga logo">
<div><h1>Bazinga</h1><p class="lead">A Discord desktop client with Equicord built in. No patching Discord, ${plugins.length} extra plugins and ${themes.length} themes.</p></div>
</header>
<div class="buttons">
<a class="button" href="https://github.com/bliper2/Bazinga/releases/latest">Download</a>
<a class="button secondary" href="https://github.com/bliper2/Bazinga">Source on GitHub</a>
</div>
<p>Works on Windows, macOS and Linux. Builds are not code-signed yet, so Windows and macOS show a warning the first time you open them. Client mods are against Discord's Terms of Service; use them at your own risk.</p>
<div class="shots">
<img src="screenshots/theme-bazinga-midnight.png" alt="The Bazinga Midnight theme" loading="lazy">
<img src="screenshots/theme-orgeco-sakura.png" alt="The Orgeco Sakura theme" loading="lazy">
</div>
<h2>Plugins (${plugins.length})</h2>
<p>Search the Plugins page in the app for "bazinga" to see them all.</p>
<input type="search" id="filter" placeholder="Search plugins" aria-label="Search plugins">
<ul class="list" id="plugins">
${pluginItems}
</ul>
<h2>Themes by orgeco (${themes.length})</h2>
<ul class="list">
${themeItems}
</ul>
<footer>Bazinga is free software under the GPL-3.0 license, built on <a href="https://github.com/Equicord/Equibop">Equibop</a>, <a href="https://github.com/Vencord/Vesktop">Vesktop</a> and <a href="https://github.com/Equicord/Equicord">Equicord</a>. See <a href="https://github.com/bliper2/Bazinga/blob/main/CREDITS.md">credits</a>.</footer>
</main>
<script>
const filter = document.getElementById("filter");
filter.addEventListener("input", () => {
    const q = filter.value.trim().toLowerCase();
    for (const li of document.querySelectorAll("#plugins li")) li.hidden = q !== "" && !li.dataset.text.includes(q);
});
</script>
</body>
</html>
`;
}

if (import.meta.main) {
    const plugins = readPlugins();
    const themes = readThemes();
    const outputs: [string, string][] = [
        [OUTPUT, buildDocument(plugins, themes)],
        [SITE_OUTPUT, buildSite(plugins, themes)]
    ];

    if (process.argv.includes("--check")) {
        const stale = outputs.filter(([file, text]) => !existsSync(file) || readFileSync(file, "utf-8") !== text);
        if (stale.length) {
            console.error(`Out of date: ${stale.map(([file]) => file.replace(ROOT, "").slice(1)).join(", ")}. Run: bun run docs`);
            process.exit(1);
        }
        console.log(`Docs are up to date (${plugins.length} plugins, ${themes.length} themes)`);
    } else {
        for (const [file, text] of outputs) writeFileSync(file, text);
        console.log(`Wrote docs/PLUGINS.md and docs/index.html (${plugins.length} plugins, ${themes.length} themes)`);
    }
}
