/*
 * Bazinga, a custom Discord desktop client
 * Copyright (c) 2026 bliper2 and Bazinga contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// Writes docs/PLUGINS.md from the plugin and theme sources, so the list never drifts from the code.
// Run `bun run docs`. `bun run docs --check` fails when the file is out of date (used in CI).

import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dirname, "../..");
const PLUGINS_DIR = join(ROOT, "plugins");
const OUTPUT = join(ROOT, "docs/PLUGINS.md");

export interface PluginInfo {
    name: string;
    description: string;
    tags: string[];
    enabledByDefault: boolean;
}

const unescape = (text: string) => text.replace(/\\(["\\])/g, "$1");

/** Reads the name, description, tags and default state from a plugin's index file. */
export function parsePlugin(source: string): PluginInfo | null {
    const head = /definePlugin\(\{\s*name:\s*"((?:[^"\\]|\\.)*)",\s*description:\s*"((?:[^"\\]|\\.)*)"/.exec(source);
    if (!head) return null;

    const tags = /tags:\s*\[([^\]]*)\]/.exec(source)?.[1].match(/"([^"]+)"/g)?.map(t => t.slice(1, -1)) ?? [];
    return {
        name: unescape(head[1]),
        description: unescape(head[2]),
        tags,
        enabledByDefault: /enabledByDefault:\s*true/.test(source)
    };
}

export function readPlugins(): PluginInfo[] {
    const plugins: PluginInfo[] = [];
    for (const entry of readdirSync(PLUGINS_DIR, { withFileTypes: true })) {
        if (!entry.isDirectory() || entry.name.startsWith("_")) continue;

        const file = ["index.tsx", "index.ts"].map(f => join(PLUGINS_DIR, entry.name, f)).find(existsSync);
        const info = file && parsePlugin(readFileSync(file, "utf-8"));
        if (!info) throw new Error(`Could not read the plugin in plugins/${entry.name}`);
        plugins.push(info);
    }
    return plugins.sort((a, b) => a.name.localeCompare(b.name));
}

export function readThemes() {
    const source = readFileSync(join(ROOT, "src/main/bundledThemes.ts"), "utf-8");
    return [...source.matchAll(/name:\s*"([^"]+)",\s*description:\s*"([^"]+)"/g)].map(m => ({ name: m[1], description: m[2] }));
}

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

export function buildDocument(plugins: PluginInfo[], themes: { name: string; description: string; }[]) {
    const rows = plugins.map(p => `| **${p.name}** | ${cell(p.description)} | ${p.enabledByDefault ? "Yes" : "No"} |`);
    const themeRows = themes.map(t => `| **${t.name}** | ${cell(t.description)} |`);

    return `# Bazinga plugins and themes

<!-- This file is generated by \`bun run docs\`. Do not edit it by hand. -->

Search the Plugins page for "bazinga" to list these in the app.

## Plugins (${plugins.length})

| Plugin | What it does | On by default |
| ------ | ------------ | ------------- |
${rows.join("\n")}

## Themes by orgeco (${themes.length})

Turn them on under Settings, Themes.

| Theme | Look |
| ----- | ---- |
${themeRows.join("\n")}
`;
}

if (import.meta.main) {
    const plugins = readPlugins();
    const themes = readThemes();
    const text = buildDocument(plugins, themes);

    if (process.argv.includes("--check")) {
        const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf-8") : "";
        if (current !== text) {
            console.error("docs/PLUGINS.md is out of date. Run: bun run docs");
            process.exit(1);
        }
        console.log(`docs/PLUGINS.md is up to date (${plugins.length} plugins, ${themes.length} themes)`);
    } else {
        writeFileSync(OUTPUT, text);
        console.log(`Wrote docs/PLUGINS.md (${plugins.length} plugins, ${themes.length} themes)`);
    }
}
